name: yolo
description: Flutter Application for Real Time Object Detection / Semantic Segmentation.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.0+1
  flutter_vision: ^1.1.4
  flutter_tts: ^4.0.2
  path_provider: ^2.1.4
  image: ^4.2.0
  permission_handler: ^11.3.1
  logger: ^2.4.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^4.0.0

flutter_icons:
  image_path: "assets/ROSCODE BOT LOGO.png.png"
  adaptive_icon_foreground: "assets/ROSCODE BOT LOGO.png.png"
  adaptive_icon_background: "#000000"
  android: true
  ios: true

flutter:
  assets:
    - assets/
  uses-material-design: true
